# Generated by Django 5.2.1 on 2025-05-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='take_ration',
            field=models.BooleanField(default=False),
        ),
    ]
