# Generated by Django 5.2.1 on 2025-05-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_token_take_ration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='take_ration',
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='noOfTokenBooked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='tokenUsed',
            field=models.BooleanField(default=False),
        ),
    ]
