# Generated by Django 5.2.1 on 2025-05-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_remove_token_take_ration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
