# Generated by Django 5.2.1 on 2025-05-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0005_token_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='in_queue',
            field=models.BooleanField(default=False),
        ),
    ]
