# Generated by Django 5.2.1 on 2025-05-24 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0006_token_in_queue'),
    ]

    operations = [
        migrations.CreateModel(
            name='itemsQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Wheat', models.IntegerField(default=0)),
                ('Rice', models.IntegerField(default=0)),
                ('Sugar', models.IntegerField(default=0)),
                ('Dal', models.IntegerField(default=0)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_itemsQuantity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
