# Generated by Django 5.2.1 on 2025-05-25 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0007_itemsquantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='itemsQuantity',
        ),
    ]
